# Generated by Django 5.2.1 on 2025-06-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_transit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='name',
            field=models.TextField(default='DEFAULT_NAME'),
        ),
        migrations.AddField(
            model_name='bus',
            name='timestamp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bus',
            name='trip_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bus',
            name='vehicle_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bus',
            name='latitude',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='longitude',
            field=models.FloatField(default=-1.0),
        ),
    ]
