# Generated by Django 5.2.2 on 2025-06-10 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_transit_app', '0002_bus_name_bus_timestamp_bus_trip_id_bus_vehicle_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('route_short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('route_long_name', models.CharField(blank=True, max_length=200, null=True)),
                ('route_desc', models.TextField(blank=True, null=True)),
                ('route_type', models.IntegerField(blank=True, null=True)),
                ('route_url', models.URLField(blank=True, null=True)),
                ('route_color', models.CharField(blank=True, max_length=6, null=True)),
                ('route_text_color', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('service_id', models.CharField(max_length=100)),
                ('trip_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('trip_headsign', models.CharField(blank=True, max_length=200, null=True)),
                ('direction_id', models.IntegerField(blank=True, null=True)),
                ('block_id', models.CharField(blank=True, max_length=100, null=True)),
                ('shape_id', models.CharField(blank=True, max_length=100, null=True)),
                ('route', models.ForeignKey(db_column='route_id', on_delete=django.db.models.deletion.CASCADE, to='core_transit_app.route')),
            ],
        ),
    ]
